CREATE TABLE `blog_articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(300) NOT NULL,
	`title` varchar(500) NOT NULL,
	`excerpt` text NOT NULL,
	`category` varchar(100) NOT NULL,
	`readTime` varchar(50) NOT NULL,
	`author` varchar(200) NOT NULL,
	`authorRole` varchar(200) NOT NULL,
	`featured` boolean NOT NULL DEFAULT false,
	`image` text NOT NULL,
	`content` text NOT NULL,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'published',
	`source` varchar(100) DEFAULT 'api',
	`externalId` varchar(300),
	`metaTitle` varchar(500),
	`metaDescription` text,
	`tags` text,
	`publishedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_articles_slug_unique` UNIQUE(`slug`)
);
